version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/www
    steps:
      - checkout

      # install dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      # build the site
      - run:
          name: Run build
          command: yarn build

  deploy_integration:
    docker:
      - image: circleci/node:latest
    working_directory: ~/www
    steps:
      - checkout

      # build the site
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run build
          command: yarn build
      # upload to S3
      - run:
          name: Install Tools
          command: sudo apt-get -y -qq install awscli
      - run:
          name: Build and push static site
          command: aws s3 sync --delete public s3://spokestack-87bc070b/www/integration

  deploy_production:
    docker:
      - image: circleci/node:latest
    working_directory: ~/www
    steps:
      - checkout

      # build the site
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Run build
          command: yarn build
      # upload to S3
      - run:
          name: Install Tools
          command: sudo apt-get -y -qq install awscli
      - run:
          name: Build and push static site
          command: aws s3 sync --delete public s3://spokestack-87bc070b/www/production

workflows:
  version: 2

  test_and_deploy:
    jobs:
      - build
      - deploy_integration:
          filters:
            branches:
              only: integration
            tags:
              only:
                - /\d+\.\d+\.\d+/
          requires:
            - build
      - deploy_production:
          filters:
            branches:
              only: production
            tags:
              only:
                - /\d+\.\d+\.\d+/
          requires:
            - build
